version: 2

jobs:
  deploy:
    docker:
      - image: circleci/node:10.15.3-stretch
    steps:
      - add_ssh_keys:
          fingerprints:
            - "3d:bd:06:12:d3:c3:d7:ca:47:8c:54:de:52:56:3d:2c"
      - checkout
      - run:
          name: Create Key
          command: echo $dp_key | base64 -di > ~/.ssh/circleci_maitrisangath
      - run:
          name: Make proper permission
          command:  chmod 400 ~/.ssh/circleci_maitrisangath
      - run:
          name: List items
          command: ls -la ~/.ssh
      - run:
          name: Add key
          command: ssh-add ~/.ssh/circleci_maitrisangath
      - run:
          name: Install packages
          command: npm install
      - run:
          name: Run linter
          command: npx vue-cli-service lint
      - run:
          name: Run tests
          command: echo "This is just sample config, please replace this command with real tests :)"
      - run:
          name: Build and minify app
          command: npm run  build
      - run:
          name: Setup Github user email
          command: git config --global user.email "adiechahari@gmail.com" 
      - run:
          name: Setup Github user name
          command: git config --global user.name "Circle CI Deployer"
      - run:
          name: Deploy to Github Pages.
          command: sh ./deploy.sh

workflows:
  version: 2
  main:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
 
