version: 2

jobs:
  deploy:
    docker:
      - image: circleci/node:10.15.3-stretch
    steps:
      - add_ssh_keys:
          fingerprints:
            - "ab:29:75:db:20:fa:99:19:22:9c:d2:e3:38:78:0e:f1"
      - checkout
      - run:
          name: Install packages
          command: npm install
      - run:
          name: Run linter
          command: npx vue-cli-service lint
      - run:
          name: Run tests
          command: echo "This is just sample config, please replace this command with real tests :)"
      - run:
          name: Build and minify app
          command: npm run  build
      - run:
          name: Git user setup
          command: 
            - git config user.email "adiechahari@gmail.com"
            - git config user.name "Circle CI Deployer"
      - run:
          name: Deploy to Github Pages.
          command: sh ./deploy.sh
workflows:
  version: 2
  main:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
 
