version: 2

jobs:
  deploy:
    docker:
      - image: circleci/node:10.15.3-stretch
    steps:
      - add_ssh_keys:
          fingerprints:
            - "3d:bd:06:12:d3:c3:d7:ca:47:8c:54:de:52:56:3d:2c"
      - checkout
      - run:
          name: Install dependancies
          command: npm install
      - run:
          name: Build resources
          command: npm run build
      - run:
          name: Move files
          command: cp -r dist ../dist
      - run:
          name: Change branch
          command: git checkout gh-pages
      - run:
          name: Change branch
          command: git pull origin gh-pages
      - run:
          name: Remove all filesfolders except dist
          command: rm -rf ./*
      - run:
          name: Remove few more hidden folder
          command: rm -rf ./.circleci ./.gitignore
      - run:
          name: Move back files
          command: cp -r ../dist/* ./
      - run:
          name: Check after moved
          command: ls -la
      - run:
          name: Initialize and commit git
          command: git config --global user.name "Harikrushna"
      - run:
          name: Initialize and commit git
          command: git config --global user.email "adiechahari@gmail.com"
      - run:
          name: Add all file changes
          command: git add --all
      - run:
          name: Making commit
          command: git commit -am "deploy"
      - run:
          name: Push to github page
          command: git push origin ph-pages --force

workflows:
  version: 2
  main:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
 
