version: 2

jobs:
  deploy:
    docker:
      - image: circleci/node:10.15.3-stretch
    steps:
      - add_ssh_keys:
          fingerprints:
            - "3d:bd:06:12:d3:c3:d7:ca:47:8c:54:de:52:56:3d:2c"
      - checkout
      - run:
          name: Checking SSH
          command: echo $dp_key | base64 -di > ~/.ssh/circleci_maitrisangath
workflows:
  version: 2
  main:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
 
