version: 2

jobs:
  deploy:
    docker:
      - image: circleci/node:10.15.3-stretch
    steps:
      - checkout
      - run:
          name: Create Key
          command: echo $dp_key | base64 -di > ~/.ssh/circleci_maitrisangath
      - run:
          name: Make proper permission
          command:  chmod 400 ~/.ssh/circleci_maitrisangath
      - run:
          name: List items
          command: ls -la ~/.ssh
      - run:
          name: Add key
          command: ssh-add ~/.ssh/circleci_maitrisangath
      - run:
          name: Check Git SSH
          command: ssh -vvv git@github.com

workflows:
  version: 2
  main:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
 
