version: 2

jobs:
  deploy:
    docker:
      - image: circleci/node:10.15.3-stretch
    steps:
      - add_ssh_keys:
          fingerprints:
            - "3d:bd:06:12:d3:c3:d7:ca:47:8c:54:de:52:56:3d:2c"
      - checkout
      - run:
          name: Check before
          command: ls -la
      - run:
          name: Check git remote
          command: git remote -v
      - run:
          name: Remove Git Dir
          command: rm -rf .git
      - run:
          name: Check after
          command: ls -la
      - run:
          name: Install dependancies
          command: npm install
      - run:
          name: Build resources
          command: npm run build
      - run:
          name: Move to dist
          command: mv dist/ .
      - run:
          name: Check after moved
          command: ls -la

workflows:
  version: 2
  main:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
 
